version: "3.9"

services:
  db:
    image: pgvector/pgvector:pg15-trixie
    restart: unless-stopped
    environment:
      PG_USER: icd10user
      PG_PASSWORD: icd10pass
      PG_DBNAME: icd10db
      PG_PORT: 5432
      PG_HOST: 0.0.0.0
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  ollama:
    image: ollama/ollama:latest
    container_name: icd10-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "ollama run llama3.2:1b"]
      interval: 5s
      timeout: 2s
      retries: 20

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://icd10user:icd10pass@db:5432/icd10db
      PG_USER: icd10user
      PG_PASSWORD: icd10pass
      PG_DBNAME: icd10db
      PG_PORT: 5432
      PG_HOST: db
      HOT_RELOAD: "true"
      LLM_BASE_URL: http://ollama:11434
      LLM_MODEL: llama3.2:1b
      LLM_TEMP: 0.2
      LLM_MAX_TOKENS: 96

    depends_on:
      - db
      - ollama
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    restart: unless-stopped
    environment:
      BACKEND_URL: http://backend:8000
    depends_on:
      - backend
    ports:
      - "8501:8501"

volumes:
  pgdata:
  ollama:
