version: "3.9"

services:
  db:
    image: pgvector/pgvector:pg15-trixie
    restart: unless-stopped
    environment:
      PG_USER: icd10user
      PG_PASSWORD: icd10pass
      PG_DBNAME: icd10db
      PG_PORT: 5432
      PG_HOST: 0.0.0.0
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://icd10user:icd10pass@db:5432/icd10db
      PG_USER: icd10user
      PG_PASSWORD: icd10pass
      PG_DBNAME: icd10db
      PG_PORT: 5432
      PG_HOST: db
      HOT_RELOAD: "true"
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    restart: unless-stopped
    environment:
      BACKEND_URL: http://backend:8000
    depends_on:
      - backend
    ports:
      - "8501:8501"

volumes:
  pgdata:
