version: "3.9"

services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: icd10user
      POSTGRES_PASSWORD: icd10pass
      POSTGRES_DB: icd10db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://icd10user:icd10pass@db:5432/icd10db
      # ...other env vars as needed...
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    restart: unless-stopped
    environment:
      BACKEND_URL: http://backend:8000
      # ...other env vars as needed...
    depends_on:
      - backend
    ports:
      - "8501:8501"

volumes:
  pgdata:
